<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Aircane.Workers</RootNamespace>
    <AssemblyName>Aircane.Workers</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aircane.Application\Aircane.Application.csproj" />
  </ItemGroup>

</Project>
