using Aircane.Application.Abstractions;

namespace Aircane.Infrastructure.Embeddings;

/// <summary>
/// A deterministic fake embedding provider for use in tests and local development
/// when no real AI provider is configured.
/// <para>
/// Embeddings are generated by seeding a <see cref="Random"/> instance with a stable
/// hash of the input text, producing a normalized unit vector. The same text always
/// produces the same vector; different texts produce different vectors.
/// </para>
/// </summary>
public sealed class FakeEmbeddingProvider : IEmbeddingProvider
{
    /// <inheritdoc />
    public int Dimensions => 768;

    /// <inheritdoc />
    public string ProviderName => "Fake";

    /// <inheritdoc />
    public Task<float[]> GenerateEmbeddingAsync(string text, CancellationToken ct = default)
        => Task.FromResult(GenerateDeterministicEmbedding(text));

    /// <inheritdoc />
    public Task<IReadOnlyList<float[]>> GenerateEmbeddingsAsync(
        IReadOnlyList<string> texts,
        CancellationToken ct = default)
    {
        var results = texts
            .Select(GenerateDeterministicEmbedding)
            .ToList();

        return Task.FromResult<IReadOnlyList<float[]>>(results);
    }

    // ── Internal helpers ──────────────────────────────────────────────────────

    private float[] GenerateDeterministicEmbedding(string text)
    {
        var seed = ComputeStableHash(text);
        var rng = new Random(seed);

        var vector = new float[Dimensions];
        for (int i = 0; i < Dimensions; i++)
        {
            // Uniform in [-1, 1] before normalization.
            vector[i] = (float)(rng.NextDouble() * 2.0 - 1.0);
        }

        Normalize(vector);
        return vector;
    }

    /// <summary>
    /// Computes a stable, deterministic 32-bit hash of <paramref name="text"/>
    /// using the FNV-1a algorithm so that the result is consistent across
    /// .NET versions (unlike <see cref="string.GetHashCode()"/>).
    /// </summary>
    private static int ComputeStableHash(string text)
    {
        unchecked
        {
            const uint fnvPrime = 16777619u;
            uint hash = 2166136261u; // FNV offset basis

            foreach (char c in text)
            {
                hash ^= (byte)(c & 0xFF);
                hash *= fnvPrime;
                hash ^= (byte)(c >> 8);
                hash *= fnvPrime;
            }

            return (int)hash;
        }
    }

    /// <summary>Normalizes <paramref name="vector"/> to unit length in-place.</summary>
    private static void Normalize(float[] vector)
    {
        double sumOfSquares = 0.0;
        foreach (var v in vector)
            sumOfSquares += (double)v * v;

        var magnitude = Math.Sqrt(sumOfSquares);
        if (magnitude < 1e-10)
            return; // Avoid division by zero for the zero vector.

        for (int i = 0; i < vector.Length; i++)
            vector[i] = (float)(vector[i] / magnitude);
    }
}
